#!/bin/bash

set -e
export PGPASSWORD=$POSTGRES_PASSWORD;

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

  CREATE USER $USER_DB WITH PASSWORD '$PASS_DB';
  CREATE DATABASE $NAME_DB;
  GRANT ALL PRIVILEGES ON DATABASE $NAME_DB TO $USER_DB;
  COMMIT;
EOSQL
